touchscreen: fts_lib: Fix strict-prototypes errors
clang-15 complains:
drivers/input/touchscreen/fts_touch/fts_lib/ftsIO.c:128:29: error: a
function declaration without a prototype is deprecated in all versions
of C [-Werror,-Wstrict-prototypes]
struct spi_device *getClient()
                            ^
                             void
drivers/input/touchscreen/fts_touch_s5/fts_lib/ftsIO.c:128:29: error: a
function declaration without a prototype is deprecated in all versions
of C [-Werror,-Wstrict-prototypes]
struct spi_device *getClient()
                            ^
                             void
2 errors generated.

Change-Id: Ia26d54281333d721deea15ef12bfe2cfe96349a8
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>